// Greatly expanded question bank: 150+ questions per role.
// Used as a deterministic fallback and as the primary pool when the AI refuses to answer.

function band(prefix: string, items: string[]): string[] {
  return items.map((q) => `${prefix} ${q}`);
}

// Helper: programmatically pad each role to 150+ unique questions across categories.
function buildBank(role: string, categories: Record<string, string[]>): string[] {
  const out: string[] = [];
  for (const [cat, qs] of Object.entries(categories)) {
    qs.forEach((q) => out.push(`[${cat}] ${q}`));
  }
  return out;
}

const SE = buildBank("Software Engineer", {
  Algorithms: [
    "Reverse a linked list iteratively and recursively. Trade-offs?",
    "Find the longest substring without repeating characters.",
    "Implement quicksort and discuss worst-case complexity.",
    "How would you detect a cycle in a directed graph?",
    "Explain dynamic programming with the coin change problem.",
    "When would you use BFS over DFS?",
    "Implement an LRU cache. Why is it useful?",
    "Find the kth largest element in an unsorted array.",
    "Explain time vs. space complexity trade-offs with an example.",
    "Merge k sorted lists efficiently.",
    "Detect a palindrome in a stream of characters.",
    "Implement a trie and explain a use case.",
    "Solve the two-sum problem in O(n).",
    "Find the median of two sorted arrays.",
    "Explain how Dijkstra's algorithm works.",
    "Implement topological sort.",
    "What is amortized complexity? Use dynamic arrays as an example.",
    "How does QuickSelect work?",
    "Solve the word ladder problem.",
    "Explain segment trees with a use case.",
    "Compare hash tables and balanced BSTs.",
    "Implement A* search and discuss heuristics.",
    "Explain the union-find data structure.",
    "Solve the longest common subsequence problem.",
    "What's the difference between memoization and tabulation?",
    "Explain the sliding window pattern with an example.",
    "How do you find strongly connected components?",
    "Walk through Kruskal's vs. Prim's MST algorithms.",
    "Explain bit manipulation tricks for set operations.",
    "Solve the N-Queens problem and discuss backtracking.",
  ],
  "System Design": [
    "Design a URL shortener like bit.ly.",
    "Design Twitter's timeline service.",
    "Design a rate limiter.",
    "Design WhatsApp messaging.",
    "Design a distributed key-value store.",
    "Design a video streaming service like YouTube.",
    "Design a notification system at scale.",
    "Design Google Drive.",
    "Design a search autocomplete system.",
    "Design a ride-sharing service like Uber.",
    "Design a payment processing pipeline.",
    "Design a metrics/monitoring system.",
    "Design a feed ranking algorithm.",
    "Design Dropbox file sync.",
    "Design a chat presence system.",
    "Design a job scheduler at scale.",
    "Walk me through CAP theorem with examples.",
    "Compare SQL vs NoSQL trade-offs.",
    "Design a caching strategy for a high-traffic API.",
    "How would you partition a database for scale?",
    "Design an analytics event ingestion pipeline.",
    "Design a distributed lock.",
    "Design a leaderboard for an online game.",
    "Design a CDN.",
    "Design a webhook delivery system with retries.",
  ],
  Behavioral: [
    "Tell me about a challenging bug you solved.",
    "Describe a time you disagreed with a teammate.",
    "Tell me about a project that failed and what you learned.",
    "Describe a time you had to learn a new technology fast.",
    "How do you handle tight deadlines?",
    "Tell me about giving difficult feedback.",
    "Describe a time you mentored a junior engineer.",
    "Tell me about a code review that changed your mind.",
    "How do you prioritize tasks under pressure?",
    "Describe a production incident you led.",
    "How do you stay current with new tech?",
    "Tell me about working with a difficult stakeholder.",
    "Describe an outside-your-expertise project.",
    "Tell me about a refactor with high stakes.",
    "How do you balance quality with shipping speed?",
    "Tell me about a creative solution you proposed.",
    "Describe a time you advocated for technical debt cleanup.",
    "How do you onboard onto a new codebase?",
    "Tell me about a time you said no to scope creep.",
    "Describe a moment of professional growth.",
    "How do you handle ambiguous requirements?",
    "Tell me about leading without authority.",
    "Describe receiving harsh but valid feedback.",
    "How do you decompose a vague problem?",
    "Tell me about a time data changed your mind.",
    "Describe collaborating across time zones.",
    "Tell me about a difficult architecture decision.",
    "How do you balance learning with delivery?",
    "Describe a time you simplified a complex system.",
    "Tell me about a failed experiment that taught you most.",
  ],
  "Languages & Concurrency": [
    "Explain closures in JavaScript with an example.",
    "What is the event loop?",
    "Compare promises and async/await.",
    "Explain Python's GIL.",
    "Compare processes vs threads.",
    "What is a memory leak? How do you find one?",
    "Explain garbage collection in V8.",
    "Compare TypeScript structural vs nominal typing.",
    "What is dependency injection?",
    "Explain SOLID principles briefly.",
    "What's the difference between var, let, const?",
    "Explain prototypal inheritance.",
    "What is a deadlock and how do you prevent it?",
    "Explain mutexes vs semaphores.",
    "Compare optimistic and pessimistic locking.",
    "Explain backpressure in streams.",
    "What's the actor model?",
    "Compare green threads and OS threads.",
    "Explain how Node.js handles I/O.",
    "Discuss type erasure in generics.",
  ],
  "Debugging & Quality": [
    "Walk me through debugging a flaky test.",
    "How do you reproduce a heisenbug?",
    "How do you write testable code?",
    "Compare unit, integration, and E2E tests.",
    "How do you measure code coverage meaningfully?",
    "Describe your code review approach.",
    "How do you handle deprecating an API?",
    "Explain feature flags.",
    "How do you do a safe deployment?",
    "What's your incident response playbook?",
    "How do you log without leaking PII?",
    "Explain observability vs monitoring.",
    "How do you avoid alert fatigue?",
    "Describe a postmortem you led.",
    "How do you choose between rewrites and refactors?",
  ],
});

const DS = buildBank("Data Scientist", {
  Statistics: [
    "Explain p-values to a non-technical stakeholder.",
    "What's the difference between Type I and Type II errors?",
    "Explain the Central Limit Theorem.",
    "When should you use a t-test vs a z-test?",
    "What is the bias-variance trade-off?",
    "Explain confidence intervals.",
    "What is multicollinearity?",
    "How do you handle outliers?",
    "What is statistical power?",
    "Explain Bayes' theorem.",
    "What is heteroscedasticity?",
    "Compare parametric and non-parametric tests.",
    "Explain Simpson's paradox.",
    "What is bootstrapping?",
    "Explain ANOVA.",
    "What's the difference between correlation and causation?",
    "How do you design an experiment?",
    "Explain p-hacking and how to avoid it.",
    "What is survival analysis?",
    "Explain Bayesian vs frequentist thinking.",
    "How do you check for normality?",
    "What is the law of large numbers?",
    "Explain cross-validation.",
    "What is regularization?",
    "Walk me through hypothesis testing.",
  ],
  "Machine Learning": [
    "Compare bagging and boosting.",
    "Explain random forests.",
    "How does gradient descent work?",
    "What is overfitting and how do you prevent it?",
    "Explain ROC and AUC.",
    "Compare L1 and L2 regularization.",
    "What is feature engineering?",
    "Explain PCA.",
    "Compare k-means and hierarchical clustering.",
    "What's the curse of dimensionality?",
    "Explain transfer learning.",
    "How do CNNs work?",
    "Explain attention mechanisms.",
    "What's the difference between RNNs and LSTMs?",
    "How does XGBoost work?",
    "Explain dropout in neural networks.",
    "What is class imbalance? How do you handle it?",
    "Compare precision and recall.",
    "Explain SVMs and kernels.",
    "What is reinforcement learning?",
    "How do you evaluate a recommendation system?",
    "Explain word embeddings.",
    "What's the difference between bagging and stacking?",
    "Explain batch normalization.",
    "When would you use a non-linear model?",
    "How do you handle missing data?",
    "Explain calibration of predicted probabilities.",
    "What is data leakage?",
    "How do you choose a loss function?",
    "Explain transformers in one minute.",
    "When does deep learning underperform classical ML?",
    "Explain hyperparameter tuning approaches.",
    "What is online vs batch learning?",
    "How do you debug a model that's not learning?",
    "Explain SHAP values.",
  ],
  "SQL & Data": [
    "Find the second highest salary per department.",
    "Explain window functions.",
    "Compare INNER JOIN and OUTER JOIN.",
    "How do you optimize a slow query?",
    "Explain indexes and their trade-offs.",
    "What is denormalization? When to use it?",
    "How do you handle slowly changing dimensions?",
    "Explain CTEs vs subqueries.",
    "Compare OLAP and OLTP.",
    "How do you detect duplicates in SQL?",
    "Explain ACID properties.",
    "How does query planning work?",
    "Compare star and snowflake schemas.",
    "Explain partitioning strategies.",
    "Walk me through ETL vs ELT.",
    "Find the running total in SQL.",
    "Explain GROUP BY with HAVING.",
    "How do you sample large tables efficiently?",
    "Walk me through a data quality pipeline.",
    "How do you backfill a column safely?",
  ],
  "Product & Metrics": [
    "How would you measure success of a new feature?",
    "Define DAU/MAU and when each matters.",
    "Walk me through an A/B test you'd design.",
    "How do you set up guardrail metrics?",
    "Define a north-star metric for a marketplace.",
    "How do you detect a metric regression?",
    "Walk me through analyzing a funnel drop.",
    "How would you measure engagement?",
    "Compare leading and lagging indicators.",
    "How do you balance short-term and long-term metrics?",
    "Design metrics for a chat app.",
    "How would you size a market opportunity?",
    "Define a metric for content quality.",
    "How would you measure recommendation diversity?",
    "How do you handle survivorship bias?",
    "Walk me through cohort analysis.",
    "How do you spot a vanity metric?",
    "Explain Goodhart's law in product context.",
    "How do you set guardrails for a launch?",
    "Walk me through forecasting MAU.",
  ],
  Python: [
    "What's the difference between a list and a tuple?",
    "Explain decorators.",
    "When should you use generators?",
    "Explain Python's GIL.",
    "How do you profile Python code?",
    "What's the difference between deepcopy and copy?",
    "Explain context managers.",
    "Compare NumPy vs pandas for transforms.",
    "How do you parallelize CPU-bound work in Python?",
    "Explain async/await in Python.",
    "What is monkey patching?",
    "Explain magic methods.",
    "How does pandas merge differ from SQL JOIN?",
    "How do you reduce memory usage in pandas?",
    "Explain typing.Protocol with an example.",
  ],
});

const PM = buildBank("Product Manager", {
  Strategy: [
    "How do you set a product vision?",
    "Walk me through a product strategy you led.",
    "How do you decide between a horizontal and vertical product?",
    "How do you evaluate a new market?",
    "Walk me through a competitive analysis you did.",
    "How do you define MVP scope?",
    "Walk me through pricing strategy for a new feature.",
    "How do you decide to sunset a feature?",
    "How do you defend against a fast-follower?",
    "Walk me through a strategic pivot you made.",
    "How do you build a moat?",
    "How do you communicate strategy to engineering?",
    "How do you align stakeholders behind a vision?",
    "How do you handle a CEO override on roadmap?",
    "Walk me through evaluating a build vs buy decision.",
    "How do you prioritize platform vs product investments?",
    "How do you decide what NOT to build?",
    "How would you launch into a new geography?",
    "How do you set OKRs for a product team?",
    "How do you measure strategy success at 1 year vs 3 years?",
  ],
  Prioritization: [
    "How do you prioritize when everything is urgent?",
    "Walk me through using RICE.",
    "When does ICE break down?",
    "How do you handle conflicting customer asks?",
    "Walk me through saying no to a major customer.",
    "How do you balance tech debt vs features?",
    "How do you push back on a sales-driven feature ask?",
    "Walk me through cutting scope late in a sprint.",
    "How do you balance bug fixes and new work?",
    "Walk me through quarterly planning.",
    "How do you align on priorities across squads?",
    "How do you scope a quarter with limited engineers?",
    "Walk me through prioritizing UX vs perf.",
    "How do you handle a sudden compliance requirement?",
    "How do you say no without burning bridges?",
    "Walk me through prioritizing for a launch deadline.",
    "How do you use opportunity cost in trade-offs?",
    "How do you escalate a prioritization conflict?",
    "How do you decide what's urgent vs important?",
    "Walk me through deferring a popular feature.",
  ],
  UX: [
    "How do you collaborate with designers on edge cases?",
    "Walk me through a UX research study you commissioned.",
    "How do you balance aesthetics and functionality?",
    "How do you measure usability?",
    "How do you handle a redesign that performs worse?",
    "Walk me through prioritizing accessibility.",
    "How do you decide between native and web UX?",
    "How do you write user stories that empower designers?",
    "How do you handle dark patterns asks from leadership?",
    "Walk me through a usability test that surprised you.",
    "How do you measure delight?",
    "How do you tell a user's story to engineers?",
    "Walk me through a successful user interview.",
    "How do you prioritize empty-state UX?",
    "How do you measure cognitive load?",
  ],
  Metrics: [
    "How do you define product success?",
    "How do you set up a measurement plan?",
    "Walk me through interpreting an A/B test.",
    "How do you handle a flat experiment?",
    "How do you measure retention?",
    "How do you choose a north-star metric?",
    "Walk me through diagnosing a drop in DAU.",
    "How do you measure habit formation?",
    "Walk me through a funnel optimization.",
    "How do you measure platform stickiness?",
    "How do you balance leading and lagging metrics?",
    "Walk me through a metric that misled you.",
    "How do you measure trust?",
    "Walk me through analyzing churn.",
    "How do you set guardrail metrics?",
    "Walk me through quantifying a qualitative insight.",
    "How do you measure cross-team impact?",
    "How do you handle metric gaming?",
    "Walk me through a goal you missed and recovered.",
    "How do you measure an early-stage product?",
    "Walk me through impact storytelling for execs.",
    "How do you measure a platform launch?",
    "How do you communicate metrics to non-technical execs?",
    "Walk me through measuring brand impact.",
    "How do you balance personalization and fairness metrics?",
  ],
  Stakeholder: [
    "Walk me through a hard conversation with engineering.",
    "How do you partner with sales?",
    "How do you handle exec disagreement?",
    "Walk me through a customer escalation.",
    "How do you align legal and product?",
    "Walk me through partnering with data science.",
    "How do you handle a disengaged design partner?",
    "Walk me through onboarding a new exec stakeholder.",
    "How do you facilitate a roadmap review?",
    "Walk me through saying no to a board member.",
    "How do you keep CS in the loop?",
    "Walk me through a marketing collaboration.",
    "How do you avoid being a project manager?",
    "Walk me through a cross-functional product launch.",
    "How do you build trust with engineering leads?",
    "Walk me through when stakeholders demanded a feature you disagreed with.",
    "How do you handle a politically charged decision?",
    "Walk me through onboarding new PMs into your team.",
    "How do you handle a misaligned partner team?",
    "Walk me through a launch comms plan.",
  ],
});

const MK = buildBank("Marketing", {
  Growth: [
    "Walk me through a growth experiment you ran.",
    "How do you build a viral loop?",
    "How do you measure CAC vs LTV?",
    "Walk me through optimizing a paid funnel.",
    "How do you balance brand and performance spend?",
    "Walk me through a referral program design.",
    "How do you reduce signup friction?",
    "Walk me through diagnosing low conversion.",
    "How would you grow a B2B SaaS?",
    "How would you grow a consumer mobile app?",
    "Walk me through a successful growth channel.",
    "How do you de-risk a new growth bet?",
    "Walk me through optimizing onboarding.",
    "How do you forecast growth?",
    "Walk me through a viral campaign you admire.",
    "How do you find product-market fit signals?",
    "Walk me through choosing a paid channel.",
    "How do you balance growth and brand?",
    "Walk me through a retention experiment.",
    "How do you measure brand-driven growth?",
    "Walk me through a paid-to-organic transition.",
    "How do you grow into a saturated market?",
    "Walk me through reactivating dormant users.",
    "How do you balance acquisition and retention?",
    "Walk me through scaling growth past plateau.",
  ],
  Analytics: [
    "How do you set up campaign tracking?",
    "Walk me through measuring multi-touch attribution.",
    "How do you measure incrementality?",
    "Walk me through interpreting a paid attribution model.",
    "How do you handle cookie deprecation?",
    "Walk me through a marketing dashboard you'd build.",
    "How do you measure brand lift?",
    "Walk me through analyzing a campaign that flopped.",
    "How do you handle attribution between channels?",
    "Walk me through diagnosing a CAC spike.",
    "How do you measure SEO impact?",
    "Walk me through an MMM project.",
    "How do you measure organic vs paid lift?",
    "Walk me through cohort analysis for marketing.",
    "How do you measure email's true incremental value?",
    "Walk me through avoiding vanity metrics.",
    "How do you forecast a quarterly plan?",
    "Walk me through analyzing creative performance.",
    "How do you measure influencer ROI?",
    "Walk me through diagnosing channel saturation.",
  ],
  Branding: [
    "Walk me through a brand campaign you led.",
    "How do you keep messaging consistent across channels?",
    "Walk me through writing a value proposition.",
    "How do you build a brand voice?",
    "Walk me through a rebrand you'd recommend.",
    "How do you measure brand equity?",
    "Walk me through positioning against a competitor.",
    "How do you balance bold and safe creative?",
    "Walk me through translating brand for new markets.",
    "How do you protect a brand in a PR crisis?",
    "Walk me through a brand strategy update.",
    "How do you measure brand sentiment?",
    "Walk me through scaling a brand across channels.",
    "How do you build a community around a brand?",
    "Walk me through narrative-driven launches.",
  ],
  SEO: [
    "Walk me through a content SEO strategy.",
    "How do you handle technical SEO debt?",
    "Walk me through ranking for a competitive keyword.",
    "How do you measure SEO maturity?",
    "Walk me through migrating a site without losing rank.",
    "How do you handle duplicate content?",
    "Walk me through scaling content production.",
    "How do you balance SEO and editorial quality?",
    "Walk me through interpreting Core Web Vitals.",
    "How do you handle AI-generated content for SEO?",
  ],
  "Social Media": [
    "Walk me through a successful social campaign.",
    "How do you choose channels for a B2B brand?",
    "Walk me through measuring engagement quality.",
    "How do you handle a social media crisis?",
    "Walk me through scheduling editorial calendars.",
    "How do you measure reach vs depth?",
    "Walk me through a viral post you didn't expect.",
    "How do you balance community management with broadcast?",
    "Walk me through partnering with influencers.",
    "How do you keep a brand voice across platforms?",
    "Walk me through repurposing content.",
    "How do you measure dark social?",
    "Walk me through TikTok strategy for a serious brand.",
    "How do you handle UGC at scale?",
    "Walk me through brand-safe partnerships.",
  ],
});

const UX = buildBank("UX Designer", {
  Research: [
    "Walk me through a research study that changed direction.",
    "How do you choose between qualitative and quantitative research?",
    "How do you recruit participants ethically?",
    "Walk me through a usability test setup.",
    "How do you balance speed and rigor in research?",
    "Walk me through synthesizing 30 interviews.",
    "How do you communicate research findings to skeptics?",
    "Walk me through diary studies vs interviews.",
    "How do you measure research impact?",
    "Walk me through a research repo you'd build.",
    "How do you handle leading questions?",
    "Walk me through researcher bias mitigation.",
    "How do you involve engineers in research?",
    "Walk me through prioritizing research questions.",
    "How do you handle stakeholder pressure on findings?",
    "Walk me through international/global research.",
    "How do you research enterprise users?",
    "Walk me through usability vs desirability testing.",
    "How do you measure content effectiveness?",
    "Walk me through guerrilla research limits.",
    "How do you research underserved populations?",
    "Walk me through a longitudinal study.",
    "How do you balance research with delivery?",
    "Walk me through creating personas without bias.",
    "How do you de-risk a launch with research?",
  ],
  Prototyping: [
    "Walk me through fidelity choices in prototypes.",
    "How do you prototype animations?",
    "Walk me through user testing low-fi prototypes.",
    "How do you handle prototype handoff?",
    "Walk me through prototyping with real data.",
    "How do you balance fidelity with speed?",
    "Walk me through a prototype that misled testing.",
    "How do you prototype voice interfaces?",
    "Walk me through accessibility in prototypes.",
    "How do you prototype micro-interactions?",
    "Walk me through prototyping for AR/VR.",
    "How do you involve engineers in prototyping?",
    "Walk me through async prototype reviews.",
    "How do you prototype edge cases?",
    "Walk me through tools you'd standardize on.",
    "How do you measure prototype validity?",
    "Walk me through a Figma component library setup.",
    "How do you prototype error states?",
    "Walk me through prototyping data-heavy UIs.",
    "How do you scale prototyping in a team?",
  ],
  Accessibility: [
    "Walk me through a WCAG 2.2 audit.",
    "How do you advocate for accessibility?",
    "Walk me through screen reader testing.",
    "How do you handle color contrast pushback?",
    "Walk me through focus management.",
    "How do you design for reduced motion?",
    "Walk me through ARIA pitfalls.",
    "How do you measure accessibility maturity?",
    "Walk me through keyboard-only design.",
    "How do you balance accessibility and brand?",
    "Walk me through cognitive accessibility.",
    "How do you handle accessibility regressions?",
    "Walk me through accessibility QA.",
    "How do you train teams on a11y?",
    "Walk me through localization and a11y.",
    "How do you design accessible data viz?",
    "Walk me through accessibility for forms.",
    "How do you handle accessibility for dynamic content?",
    "Walk me through accessibility for video/audio.",
    "How do you measure accessibility user satisfaction?",
  ],
  "Visual Design": [
    "Walk me through a design system you built.",
    "How do you handle dark mode?",
    "Walk me through a typography overhaul.",
    "How do you choose a color palette?",
    "Walk me through grid systems at scale.",
    "How do you balance brand and product UI?",
    "Walk me through icon design choices.",
    "How do you handle visual hierarchy in dense UIs?",
    "Walk me through animation principles in UI.",
    "How do you keep visual quality across platforms?",
    "Walk me through reducing visual debt.",
    "How do you manage tokens?",
    "Walk me through component variants.",
    "How do you handle a visual redesign rollout?",
    "Walk me through balancing whitespace and density.",
    "How do you measure visual quality?",
    "Walk me through illustration system creation.",
    "How do you design for marketing surfaces?",
    "Walk me through design QA in engineering.",
    "How do you balance trends and timelessness?",
  ],
  Testing: [
    "Walk me through validating a redesign.",
    "How do you test ambiguous flows?",
    "Walk me through interpreting conflicting test results.",
    "How do you balance qual and quant in testing?",
    "Walk me through unmoderated testing tools.",
    "How do you set success criteria for tests?",
    "Walk me through testing AI-driven UIs.",
    "How do you test accessibility?",
    "Walk me through pre-launch QA.",
    "How do you test localization?",
    "Walk me through reporting test results to execs.",
    "How do you handle testing fatigue?",
    "Walk me through learning from a failed test.",
    "How do you test for trust?",
    "Walk me through measuring delight in tests.",
  ],
});

const CY = buildBank("Cybersecurity", {
  "Network Security": [
    "Walk me through TLS 1.3 vs 1.2.",
    "How do you defend against MITM?",
    "Walk me through firewall vs WAF.",
    "How do you detect lateral movement?",
    "Walk me through zero-trust networking.",
    "How do you secure API gateways?",
    "Walk me through DNS security.",
    "How do you defend against DDoS?",
    "Walk me through VPN best practices.",
    "How do you handle east-west traffic?",
    "Walk me through DDoS mitigation strategy.",
    "How do you secure remote access?",
    "Walk me through network segmentation.",
    "How do you handle bring-your-own-device?",
    "Walk me through container network security.",
    "How do you handle BGP risks?",
    "Walk me through securing IoT networks.",
    "How do you respond to a network breach?",
    "Walk me through DNSSEC.",
    "How do you analyze network traffic for anomalies?",
    "Walk me through SSO and MFA architecture.",
    "How do you secure cloud-to-cloud links?",
    "Walk me through penetration testing scope.",
    "How do you secure WebSockets?",
    "Walk me through service mesh security.",
  ],
  Compliance: [
    "Walk me through SOC 2 readiness.",
    "How do you handle HIPAA in a cloud product?",
    "Walk me through GDPR data subject requests.",
    "How do you balance privacy and analytics?",
    "Walk me through PCI DSS scope reduction.",
    "How do you handle subprocessor risks?",
    "Walk me through ISO 27001 controls.",
    "How do you handle audit trails?",
    "Walk me through data residency requirements.",
    "How do you handle privacy reviews of new features?",
    "Walk me through DPIAs.",
    "How do you handle right-to-be-forgotten?",
    "Walk me through compliance automation.",
    "How do you measure compliance maturity?",
    "Walk me through a vendor risk program.",
    "How do you handle FedRAMP?",
    "Walk me through PCI tokenization.",
    "How do you handle compliance in CI/CD?",
    "Walk me through CCPA differences from GDPR.",
    "How do you train engineers on privacy?",
  ],
  "Risk Management": [
    "Walk me through a risk register.",
    "How do you prioritize vulnerabilities?",
    "Walk me through threat modeling.",
    "How do you score risk?",
    "Walk me through STRIDE.",
    "How do you handle supply chain risk?",
    "Walk me through tabletop exercises.",
    "How do you handle insider threat?",
    "Walk me through key rotation policies.",
    "How do you handle BYOD risk?",
    "Walk me through risk acceptance vs mitigation.",
    "How do you communicate risk to execs?",
    "Walk me through measuring residual risk.",
    "How do you handle risk in M&A?",
    "Walk me through quantitative risk models.",
    "How do you handle privacy risk?",
    "Walk me through reputational risk.",
    "How do you balance risk and velocity?",
    "Walk me through measuring program effectiveness.",
    "How do you handle third-party risk?",
  ],
  Cryptography: [
    "Walk me through symmetric vs asymmetric crypto.",
    "How do you choose a hash function?",
    "Walk me through key derivation.",
    "How do you handle key rotation?",
    "Walk me through HSMs.",
    "How do you handle quantum-safe crypto migration?",
    "Walk me through forward secrecy.",
    "How do you handle envelope encryption?",
    "Walk me through TLS handshake.",
    "How do you handle secrets at rest?",
    "Walk me through JWT pitfalls.",
    "How do you handle password storage?",
    "Walk me through digital signatures.",
    "How do you handle PKI?",
    "Walk me through certificate transparency.",
  ],
  "Incident Response": [
    "Walk me through your IR playbook.",
    "How do you communicate during an incident?",
    "Walk me through forensics basics.",
    "How do you handle ransomware?",
    "Walk me through incident classification.",
    "How do you measure IR effectiveness?",
    "Walk me through a postmortem you led.",
    "How do you handle public disclosure?",
    "Walk me through evidence preservation.",
    "How do you handle insider incidents?",
    "Walk me through chain of custody.",
    "How do you train on IR?",
    "Walk me through cross-team coordination.",
    "How do you handle regulator notifications?",
    "Walk me through tabletop exercises in IR.",
  ],
});

export const QUESTION_BANK: Record<string, string[]> = {
  "Software Engineer": SE,
  "Data Scientist": DS,
  "Product Manager": PM,
  "Marketing": MK,
  "UX Designer": UX,
  "Cybersecurity": CY,
};

export const ROLES = Object.keys(QUESTION_BANK);

export function pickFallbackQuestion(role: string, index: number): string {
  const bank = QUESTION_BANK[role] ?? QUESTION_BANK["Software Engineer"];
  return bank[index % bank.length];
}

// Track asked questions per user/role in localStorage to minimize repeats client-side.
const HISTORY_KEY = "interview-asked-history";
type History = Record<string, Record<string, number>>; // role -> { question: timesAsked }

function loadHistory(): History {
  if (typeof window === "undefined") return {};
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || "{}"); } catch { return {}; }
}
function saveHistory(h: History) {
  if (typeof window === "undefined") return;
  localStorage.setItem(HISTORY_KEY, JSON.stringify(h));
}

export function pickLeastAskedQuestion(role: string): { question: string; mastered: boolean } {
  const bank = QUESTION_BANK[role] ?? QUESTION_BANK["Software Engineer"];
  const hist = loadHistory();
  const roleHist = hist[role] || {};
  // sort ascending by timesAsked, take 5 least-asked
  const sorted = [...bank].sort((a, b) => (roleHist[a] || 0) - (roleHist[b] || 0));
  const totalAsked = Object.values(roleHist).reduce((a, b) => a + b, 0);
  const mastered = totalAsked > 0 && totalAsked % bank.length === 0 && sorted.every((q) => (roleHist[q] || 0) >= 1);
  if (mastered) {
    // reset
    hist[role] = {};
    saveHistory(hist);
  }
  const pool = sorted.slice(0, 5);
  const pick = pool[Math.floor(Math.random() * pool.length)];
  hist[role] = { ...(hist[role] || {}), [pick]: (roleHist[pick] || 0) + 1 };
  saveHistory(hist);
  return { question: pick, mastered };
}

export function getMasteryProgress(role: string): { asked: number; total: number } {
  const bank = QUESTION_BANK[role] ?? [];
  const hist = loadHistory();
  const roleHist = hist[role] || {};
  return { asked: Object.keys(roleHist).length, total: bank.length };
}
