export type SkillRole = {
  id: string;
  title: string;
  emoji: string;
  description: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  duration: string;
  stages: { name: string; questions: string[] }[];
};

const make = (
  id: string,
  title: string,
  emoji: string,
  desc: string,
  difficulty: 1 | 2 | 3 | 4 | 5,
  technical: string[],
  behavioral: string[],
  scenario: string[],
): SkillRole => ({
  id, title, emoji, description: desc, difficulty, duration: "45 min",
  stages: [
    { name: "Technical Competence", questions: technical },
    { name: "Behavioral & Soft Skills", questions: behavioral },
    { name: "Live Problem-Solving", questions: scenario },
  ],
});

export const SKILL_ROLES: SkillRole[] = [
  make("frontend", "Frontend Developer", "💻",
    "React, TypeScript, accessibility & performance.", 3,
    ["Explain the React reconciliation algorithm and when it causes performance issues.",
     "Walk through how you'd debug a 3-second LCP on a marketing page.",
     "When would you reach for a state machine over Context + useReducer?"],
    ["Describe a time you pushed back on a designer's spec. What happened?",
     "Tell me about a feature you shipped that you later regretted.",
     "How do you onboard a junior engineer to a legacy codebase?"],
    ["You inherit a dashboard that takes 14 seconds to render 5,000 rows. You have 3 days. What do you do?"]),
  make("backend", "Backend Developer", "⚙️",
    "APIs, databases, distributed systems.", 4,
    ["Design a rate limiter for an API with 100M requests/day.",
     "Walk through how you'd debug a memory leak in a Node service.",
     "When is eventual consistency the right trade-off?"],
    ["Describe a production incident you led. What did you learn?",
     "How do you decide when to add a new microservice vs extend an existing one?",
     "Tell me about a code review where you completely changed your mind."],
    ["Your main DB is at 95% disk and writes are slowing. You can't downtime. What's your next 30 minutes?"]),
  make("data-analyst", "Data Analyst", "📊",
    "SQL, statistics, business storytelling.", 3,
    ["Write a SQL query to find the top 3 products per category by revenue.",
     "Explain p-values to a marketing exec who's never heard of them.",
     "When does correlation tell you something useful for the business?"],
    ["Tell me about a time stakeholders ignored your analysis. What did you do?",
     "How do you handle a deadline when the data isn't clean?",
     "Describe a dashboard that failed. Why?"],
    ["Revenue dropped 22% week-over-week. The CEO wants an explanation in 1 hour. Walk me through it."]),
  make("product-manager", "Product Manager", "🎯",
    "Strategy, prioritization, cross-functional leadership.", 4,
    ["How would you measure the success of a new onboarding flow?",
     "Walk through your prioritization framework for a quarter with 30 requests.",
     "When do you ship 80% and iterate vs hold for 100%?"],
    ["Describe a time you said no to your CEO. How?",
     "Tell me about a project that missed its goal. What did you learn?",
     "How do you align engineering and design when they disagree?"],
    ["Your lead engineer quits 2 weeks before launch. You have 3 minutes — what do you do?"]),
  make("ux-designer", "UX Designer", "🎨",
    "Research, IA, interaction design, design systems.", 3,
    ["How do you decide between a usability test and a survey?",
     "Walk through your process from problem to high-fidelity prototype.",
     "When is a design system holding the team back?"],
    ["Tell me about a time research contradicted what you believed.",
     "How do you defend a controversial design decision to engineering?",
     "Describe a critique session that went badly. What changed?"],
    ["Sign-up conversion dropped 18% after your redesign launched. You have 30 minutes to brief the team."]),
  make("sales-rep", "Sales Representative", "💼",
    "Discovery, objection handling, closing.", 2,
    ["Walk me through your discovery framework on a $50K deal.",
     "How do you qualify out of a deal that looks great on paper?",
     "What's your method for handling 'send me a proposal' early in the call?"],
    ["Tell me about your worst lost deal. What did you learn?",
     "How do you motivate yourself in a 3-month dry spell?",
     "Describe a time a prospect lied to you. How did you handle it?"],
    ["A champion goes dark 2 weeks before quarter-end on a deal worth 30% of your quota. Next moves?"]),
  make("customer-success", "Customer Success Manager", "🤝",
    "Renewals, expansion, account health.", 3,
    ["How do you measure account health beyond NPS?",
     "Walk through how you'd run a 90-day onboarding for a $200K customer.",
     "When do you escalate to the exec sponsor vs handle in-account?"],
    ["Describe a churn you couldn't prevent. What did you change after?",
     "Tell me about a time you upsold without selling.",
     "How do you build trust with a hostile new contact at a renewing account?"],
    ["Your largest account just lost their executive sponsor and renewal is in 45 days. Plan your week."]),
  make("marketing", "Marketing Coordinator", "📣",
    "Campaign execution, brand voice, measurement.", 2,
    ["How do you measure the ROI of a brand campaign?",
     "Walk through how you'd launch a product in 4 weeks with $20K.",
     "When does paid acquisition stop scaling and what do you do?"],
    ["Describe a campaign that flopped. What did you learn?",
     "How do you handle a creative review where everyone disagrees?",
     "Tell me about a time you defended brand voice against a sales request."],
    ["A competitor just launched a copycat product. Your CMO wants a response by EOD. What's your plan?"]),
  make("project-manager", "Project Manager", "🗂️",
    "Scope, risk, stakeholder communication.", 3,
    ["How do you decide between waterfall and agile for a new project?",
     "Walk through how you'd build a risk register for a 6-month build.",
     "When is scope creep actually good?"],
    ["Tell me about a project that ran 50% over budget. What happened?",
     "How do you give bad news to a steering committee?",
     "Describe a conflict between two leads you had to resolve."],
    ["Two weeks from go-live, a critical dependency slips by a month. Talk me through your next 24 hours."]),
  make("business-analyst", "Business Analyst", "📈",
    "Requirements, process design, gap analysis.", 3,
    ["Walk through how you'd document requirements for a new CRM.",
     "How do you decide between a build, buy, or partner recommendation?",
     "What's your favorite framework for process mapping?"],
    ["Describe a time stakeholders gave you contradictory requirements. What did you do?",
     "How do you push back when an exec wants a feature that won't move the metric?",
     "Tell me about a recommendation you made that was wrong."],
    ["A C-level asks why the new ERP project is 4 months late. You have 5 minutes. What do you say?"]),
];

export function getRole(id: string) {
  return SKILL_ROLES.find((r) => r.id === id);
}
